apiVersion: v1
kind: Service
metadata: 
  name: myapp-service
spec: 
  nodeName: node02
  ports: 
    - 
      nodePort: 30008
      port: 80
      targetPort: 80
  selector: 
    app: myapp
  type: NodePort
                                                                                                                                            
~                                                                                                                                                                                     
~                                   
